### PR TITLE
docs: add homebrew

### PR DESCRIPTION
**Pull request by SylvanFranklin**
Added instructions for homebrew tap that bypasses code signing by disabling quarantine. I don't know if you want the instructions in the main part of the README or somewhere else but this seems suitable.

### CODE REVIEW

**Comment by ci010** [comment]
hey, i just review the brew tap repo. 
i think it's better to create a repo under voxelum org for tap so we could automate the update of rb file.

also i think the current zap command contains your username.

**Comment by SylvanFranklin** [comment]
I will make a couple changes to the PR and transfer ownership of the tap to this org.

**Comment by SylvanFranklin** [comment]
I will make a couple changes to the PR and transfer ownership of the tap to this org, however currently I do not have permissions to transfer a repo to you. idk if you wanna do it like that or just clone, remove git, and create your own repo for it. If you wanna add me a contributor on the tap repo I can help with more complex maintenance.

**Comment by ci010** [comment]
I just created the repo https://github.com/[Voxelum/homebrew-xmcl](https://github.com/Voxelum/homebrew-xmcl).

I wanted to fork you original one, but I found you just delete it

**Comment by SylvanFranklin** [comment]
Ahh I see. I just made it private when I was trying to get around the ownerhip transfer restrictions. I will make it public again so that you can fork it. FYI the link that you posted appears to broken and may only contain the license, it should be now public again, cheers: [https://github.com/SylvanFranklin/homebrew-xmcl](https://github.com/SylvanFranklin/homebrew-xmcl)

**Comment by ci010** [comment]
> Ahh I see. I just made it private when I was trying to get around the ownerhip transfer restrictions. I will make it public again so that you can fork it. FYI the link that you posted appears to broken and may only contain the license, it should be now public again, cheers: https://github.com/SylvanFranklin/homebrew-xmcl

https://github.com/Voxelum/homebrew-xmcl forked

**Comment by SylvanFranklin** [comment]
Awesome this should be good to go, let me know if you want any further clarification, or help with version update script etc.

**Pull request merged**
