### PR TITLE
Update ru.yaml

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by ci010** [comment]
Hi Vanja, I just refactored a lot on i18n namespace, renaming the keys and removing lots of unused keys. Do you feel it's clearer for a translator to understand the key? (I think some of the old translation keys are mixed together).

Also, Currently, we can put the i18n block on vue file (under the page). So, you can know where the key is applied. Currently, only several pages apply this. They are

- xmcl-keystone-ui\src\windows\main\views\AppExportDialogInstanceFiles.vue
- xmcl-keystone-ui\src\windows\main\views\AppFeedbackDialog.vue
- xmcl-keystone-ui\src\windows\main\views\AppLaunchBlockedDialog.vue
- xmcl-keystone-ui\src\windows\main\views\BaseSetting.vue
- xmcl-keystone-ui\src\windows\main\views\BaseSettingGeneral.vue
- xmcl-keystone-ui\src\windows\main\views\Curseforge.vue
- xmcl-keystone-ui\src\windows\main\views\CurseforgeProject.vue
- xmcl-keystone-ui\src\windows\main\views\CurseforgeProjectDestMenu.vue
- xmcl-keystone-ui\src\windows\main\views\CurseforgeProjectFiles.vue
- xmcl-keystone-ui\src\windows\main\views\CurseforgeProjectFilesTile.vue
- xmcl-keystone-ui\src\windows\main\views\CurseforgeProjectHeader.vue
- xmcl-keystone-ui\src\windows\main\views\GameSetting.vue
- xmcl-keystone-ui\src\windows\main\views\HomeJavaIssueDialog.vue
- xmcl-keystone-ui\src\windows\main\views\HomeLaunchMultiInstanceDialog.vue
- xmcl-keystone-ui\src\windows\main\views\MultiplayerDialogInitiate.vue
- xmcl-keystone-ui\src\windows\main\views\MultiplayerDialogReceive.vue
- xmcl-keystone-ui\src\windows\main\views\SaveCopyToDialog.vue
- xmcl-keystone-ui\src\windows\main\views\SettingAppearance.vue
- xmcl-keystone-ui\src\windows\main\views\SettingGeneral.vue
- xmcl-keystone-ui\src\windows\main\views\SettingUpdate.vue

This is experimental. I think I'll put more i18n block on `dialogs`, since the translation content in dialog won't be shared by other pages. For shared translation, it's better to put them in locales files.

**Comment by vanja-san** [comment]
@ci010 Hi! I need to translate something? I'm confused, there are more files now. 😅

**Comment by ci010** [comment]
> @ci010 Hi! I need to translate something? I'm confused, there are more files now. 😅

Kind of, I just want to mention that we can put the translation right inside the `.vue` file. For example:
image

**Review by ci010 — APPROVED** [review]

**Comment by vanja-san** [comment]
@ci010 I understand there will be more files to translate?

**Pull request merged**
