### PR TITLE
feat: virtualized file list for instance update dialog

### PR DESCRIPTION
**Pull request by paring-chan**
## What's changed:
- More compact UI
- Virtual scrolling of file tree by utilizing [@tanstack/virtual](https://github.com/TanStack/virtual): this reduces lag if there's massive amounts of files
- Added some utilities to flatten a tree

image

### CODE REVIEW

**Comment by ci010** [comment]
Soooooo nice 👍 , that's the workitem I want to do but do not have time.

I just wonder did you try the vuetify v-virtual-scroll component? If that works, then we don't need an additional package.

**Comment by paring-chan** [comment]
I tried vuetify's virtual scroll component, but it doesn't support specifying an scroll container

**Comment by paring-chan** [comment]
I found creating modpack is broken, I will fix it

**Comment by ci010** [comment]
I found you could also improve the perf by moving the sort out in `instanceFileNodeData.ts`

```diff
  function buildEdges(cwd: InstanceFileNode<T>[], filePaths: string[], parent: string, file: InstanceFileNode<T>) {
    const remained = filePaths.slice(1)
    if (remained.length > 0) { // edge
      const name = filePaths[0]
      let edgeNode = cwd.find(n => n.name === name)
      const current = parent ? (parent + '/' + name) : name
      if (!edgeNode) {
        edgeNode = markRaw({
          name,
          path: current,
          size: 0,
          children: [],
        })
        cwd.push(edgeNode)
      }
      buildEdges(edgeNode.children!, remained, current, file)
-      if (sort) {
-        edgeNode.children?.sort((a, b) => a.path.localeCompare(b.path))
-      }
    } else { // leaf
      cwd.push(markRaw(file))
    }
  }

function update(files: InstanceFileNode<T>[]) {
    const leavesNodes = files
    const result: InstanceFileNode<T>[] = []
+    leavesNodes.sort((a, b) => a.path.localeCompare(b.path))
    for (const file of leavesNodes) {
      buildEdges(result, file.path.split('/'), '', file)
    }
    leaves.value = leavesNodes
    nodes.value = result
  }
```

This can speed up the tree build.

Sorry, the manifest tree code is implemented in rush. The code quality is really bad 😂.

**Comment by ci010** [comment]
> I found creating modpack is broken, I will fix it

Also the `AppExportDailog.vue` and `AppShareInstanceDialog.vue`. If you don't have time to fix I will take a look. You might want to split it into a new component if you want to check in first.

**Comment by paring-chan** [comment]
fixed all InstanceManifestFileTree usages  and applied your suggestions! thank you

**Comment by ci010** [comment]
I pushed some change to improve the export dialog perf. You can also try to see if that work for you. This PR LGFM now. I can merge it if you don't want to add other things

**Comment by paring-chan** [comment]
I'm ok to merge

**Pull request merged**
